# Generated by Django 3.2.7 on 2021-09-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='personal_detail',
        ),
    ]
