# Generated by Django 3.2.7 on 2021-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_detail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='backgroud_pic',
            field=models.ImageField(blank=True, upload_to='my_pics/'),
        ),
    ]
