# Generated by Django 3.2.7 on 2021-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_detail_backgroud_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='backgroud_pic',
            field=models.ImageField(upload_to='my_pics/'),
        ),
    ]
