# Generated by Django 3.2.7 on 2021-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_project_proj_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_pic',
            field=models.ImageField(upload_to='my_project_pics/'),
        ),
    ]
