# Generated by Django 3.2.7 on 2022-05-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20220508_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acomplishment',
            name='personal_detail',
        ),
    ]
