# Generated by Django 3.2.7 on 2022-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20220508_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='_backgroud_pic',
            field=models.ImageField(blank=True, default='my_pics/avatar.png', null=True, upload_to='my_pics/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='_profile_pic',
            field=models.ImageField(blank=True, default='my_pics/avatar.png', null=True, upload_to='my_pics/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='skills',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='_proj_pic',
            field=models.ImageField(blank=True, default='my_project_pics/cover.jpg', null=True, upload_to='my_project_pics/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
